version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: honeydock-elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - honeydock

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.4
    container_name: honeydock-logstash
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    networks:
      - honeydock
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    container_name: honeydock-kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - honeydock
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.4
    container_name: honeydock-filebeat
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logdata:/honeydock/logs
    networks:
      - honeydock
    depends_on:
      - logstash

volumes:
  esdata:
    driver: local
  logdata:

networks:
  honeydock:
    driver: bridge
