version: '3'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.0.0
    container_name: filebeat-honeydock
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./var/lib/docker/containers:/hostfs/var/lib/docker/containers:rw
    networks:
      - honeydock

networks:
  honeydock:
    driver: bridge
