version: '3'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.4
    container_name: honeydock-filebeat
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./var/lib/docker/containers:/hostfs/var/lib/docker/containers:rw
    networks:
      - honeydock
    depends_on:
      - logstash

networks:
  honeydock:
    driver: bridge
