## Docker defaults
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

## Disabling X-Pack Features
## https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html
## https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.reporting.enabled: false
xpack.security.enabled: false